services:
  postgres:
    image: postgres:15
    env_file:
      - ./.env # Use the same .env file for both services
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  node-api:
    build:
      context: . #. means this docker-compose is inside the node api home directory, in this scenario, you can even abandon this option.
      dockerfile: Dockerfile
    ports:
      - "7321:7321"
    depends_on:
      - postgres
    env_file:
      - ./.env # Use the same .env file for both services
    working_dir: /app/
    volumes:
      - .:/app/
      - /app/node_modules
    command: npm run dev

volumes:
  postgres-data: